debug:
  verbose: True
  visualize: True
  save_images: True

camera:
  info_topic: '/camera/color/camera_info'
  image_topic: '/camera/color/image_raw'
  depth_topic: '/camera/depth/image_rect_raw'
  camera_frame: 'camera_link'
  world_frame: 'camera_link'

model:
  model: Mask_RCNN
  weights: 'model_field_day1.pth'
  score_threshold: 0.6
  device: -1

stalk:
  minimum_mask_area: 30
  feature_point_offset: 10
  optimal_grasp_height: 0.11
  cluster_threshold: 0.1
  minimum_stalk_width: 12
  maximum_stalk_width: 45

  min_x: -1
  max_x: 1
  min_y: -1
  max_y: 1 
  min_z: 0
  max_z: 0.6